### ISSUE TITLE
Transformed `any_view` fails with category

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#818]
Hi everyone,

If I apply `view::transform` to `any_view` with a category, the result is strange. Consider the following code:

```c++
#include <range/v3/view/any_view.hpp>
#include <range/v3/view/transform.hpp>
#include <iostream>
#include <vector>

struct A {
    int x;
};

int main()
{
    std::vector<A> xs{{3}, {2}, {1}};
    ranges::any_view<A> xs_view{xs};
    ranges::any_view<A, ranges::category::random_access> xs_ra_view{xs};
    std::cout << (ranges::view::transform(xs, &A::x)) << '\n';  // ok
    std::cout << (ranges::view::transform(xs_view, &A::x)) << '\n';  // ok
    std::cout << (ranges::view::transform(xs_ra_view, &A::x)) << '\n';  // bad
    std::cout << (ranges::view::transform(xs_ra_view, [](A a) { return a.x; })) << '\n';  // ok
}
```

Output:
```
[3,2,1]
[3,2,1]
[32764,32764,32764]
[3,2,1]
```
The third line does not appear to be correct. The same happens for all categories except for `input`. Am I missing something?

Thanks!

**Comment by gnzlbg** [comment]
> Note that -fsanitize=address does not detect anything, but valgrind does:

AddressSanitizer does not work with memory that is on the stack. MemorySanitizer is the tool that does this.

**Comment by FloopCZ** [comment]
> AddressSanitizer does not work with memory that is on the stack. MemorySanitizer is the tool that does this.

Of course. :smile: That one naturally detects the issue as well.
```
[floop@pine /tmp ]$ MSAN_SYMBOLIZER_PATH=/usr/local/bin/llvm-symbolizer clang++ -Wall -O0 -g -std=c++17 -fsanitize=memory -fno-omit-frame-pointer view.cpp && ./a.out
Uninitialized bytes in __interceptor_memcmp at offset 72 inside [0x7ffffcb276d0, 256)
==29398==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7efdcadebecc in std::ctype<char>::_M_widen_init() const /build/gcc/src/gcc/libstdc++-v3/src/c++11/ctype.cc:98
    #1 0x7efdcae4add8 in std::ctype<char>::widen(char) const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/locale_facets.h:876
    #2 0x7efdcae4add8 in std::basic_ios<char, std::char_traits<char> >::widen(char) const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_ios.h:450
    #3 0x7efdcae4add8 in std::basic_ios<char, std::char_traits<char> >::fill() const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_ios.h:374
    #4 0x7efdcae4add8 in std::ostream& std::ostream::_M_insert<long>(long) /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:73
    #5 0x5638814198b5 in std::ostream& ranges::v3::view_interface<ranges::v3::iter_transform_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > >, __gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > > >, ranges::v3::indirected<int A::*> >, (ranges::v3::cardinality)-1>::print_<std::ostream, ranges::v3::iter_transform_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > >, __gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > > >, ranges::v3::indirected<int A::*> > const, 42, 0>(std::ostream&, ranges::v3::iter_transform_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > >, __gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > > >, ranges::v3::indirected<int A::*> > const&) /home/floop/.local/include/range/v3/view_interface.hpp:393:30
    #6 0x563881404e53 in std::ostream& ranges::v3::operator<< <ranges::v3::iter_transform_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > >, __gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > > >, ranges::v3::indirected<int A::*> >, 42, 0>(std::ostream&, ranges::v3::iter_transform_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > >, __gnu_cxx::__normal_iterator<A*, std::vector<A, std::allocator<A> > > >, ranges::v3::indirected<int A::*> > const&) /home/floop/.local/include/range/v3/view_interface.hpp:406:24
    #7 0x5638813fd178 in main /tmp/view.cpp:15:15
    #8 0x7efdc9e13f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #9 0x56388137e539 in _start (/tmp/a.out+0x1c539)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /build/gcc/src/gcc/libstdc++-v3/src/c++11/ctype.cc:98 in std::ctype<char>::_M_widen_init() const
Exiting
```

**Comment by ericniebler** [comment]
Thanks, @gnzlbg!

**Comment by gnzlbg** [comment]
I think you meant to thank @FloopCZ , I didn't do anything :D

**Comment by gnzlbg** [comment]
@ericniebler did a patch landed for this?

**Comment by FloopCZ** [comment]
@ericniebler This is probably a misunderstanding, we have the stack traces, but the issue persists. :-)

**Comment by FloopCZ** [comment]
Thank you @ericniebler, the `RefVal` template parameter was the thing I missed and it fixes the output. Strange things are happening though, e.g., these few lines fail with memory sanitizer enabled:
```c++
#include <range/v3/view/any_view.hpp>
#include <iostream>
#include <vector>
int main()
{
    std::vector<int> xs{3, 2, 1};
    ranges::any_view<int&> xs_view{xs};

    std::vector<int> ys{1, 2, 3};
    std::cout << ranges::view::all(ys) << '\n';
}
```

Output:
```bash
[floop@pine /tmp ]$ clang++ -Wall -O0 -g -std=c++17 -fsanitize=memory -fno-omit-frame-pointer view.cpp &&  ./a.out
Uninitialized bytes in __interceptor_memcmp at offset 248 inside [0x7ffc9db8e360, 256)
==31622==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7ff2ad40decc in std::ctype<char>::_M_widen_init() const /build/gcc/src/gcc/libstdc++-v3/src/c++11/ctype.cc:98
    #1 0x7ff2ad46cdd8 in std::ctype<char>::widen(char) const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/locale_facets.h:876
    #2 0x7ff2ad46cdd8 in std::basic_ios<char, std::char_traits<char> >::widen(char) const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_ios.h:450
    #3 0x7ff2ad46cdd8 in std::basic_ios<char, std::char_traits<char> >::fill() const /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_ios.h:374
    #4 0x7ff2ad46cdd8 in std::ostream& std::ostream::_M_insert<long>(long) /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:73
    #5 0x5626012e5c23 in std::ostream& ranges::v3::view_interface<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >, (ranges::v3::cardinality)-1>::print_<std::ostream, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > > const, 42, 0>(std::ostream&, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > > const&) /home/floop/.local/include/range/v3/view_interface.hpp:393:30
    #6 0x5626012da683 in std::ostream& ranges::v3::operator<< <ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >, 42, 0>(std::ostream&, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > > const&) /home/floop/.local/include/range/v3/view_interface.hpp:406:24
    #7 0x5626012d9868 in main /tmp/view.cpp:10:15
    #8 0x7ff2ac435f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #9 0x56260125abb9 in _start (/tmp/a.out+0x1bbb9)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /build/gcc/src/gcc/libstdc++-v3/src/c++11/ctype.cc:98 in std::ctype<char>::_M_widen_init() const
Exiting
```

Note that the last two lines are independent of the first two lines. However, if you comment out the line `ranges::any_view<int&> xs_view{xs};`, that is never used anyway, no error is detected (??). The same is true for `std::cout << ranges::view::all(ys) << '\n';`.

That is disturbing, however, if compiled without the memory sanitizer, `valgrind` detects no error. (Maybe this is just a compiler bug.)

```bash
[floop@pine /tmp ]$ clang++ -vclang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
```

Is anyone able to reproduce this? Thanks.

**Comment by ericniebler** [comment]
I've also seen sanitizer errors from libstdc++'s ctype implementation. I have never investigated. I don't believe this has anything to do with range-v3, though.

**Comment by gnzlbg** [comment]
>  these few lines fail with memory sanitizer enabled:

Did you compile your std library and c++abi with the memory sanitizer enabled?

**Comment by FloopCZ** [comment]
@gnzlbg You are right and with `msan`-enabled `libc++`, everything is fine. It is probably just a false positive caused by `libstdc++` without `msan` support.

Thank you both @ericniebler and @gnzlbg.
